### ISSUE TITLE
Unnecessary error in xarray_wrapper when there is only one channel.

### ISSUE THREAD

**Issue by jpolz** [pycomlink/pycomlink#86]
Error when using pycomlink==0.3.2 and a dataset with only one channel:

```
/home/polz-j/miniconda3/lib/python3.7/site-packages/numba/core/dispatcher.py:238: UserWarning: Numba extension module 'sparse._numba_extension' failed to load due to 'ModuleNotFoundError(No module named 'numba.targets')'.
  entrypoints.init_all()

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-36-d4e1a4160369> in <module>
----> 1 cml['baseline'] = pycml.processing.baseline.baseline_constant(trsl=cml.trsl, wet=cml.wet, n_average_last_dry=5)
      2 
      3 fig, ax = plt.subplots(figsize=(10,3))
      4 
      5 cml.trsl.sel(time=slice('2020-08-01', '2020-08-30')).plot.line(x='time', alpha=0.5)

~/miniconda3/lib/python3.7/site-packages/pycomlink/processing/xarray_wrapper.py in inner(*args, **kwargs)
     46                     data=func(**kwargs),
     47                     dims=("time"),
---> 48                     coords={"time": kwargs[vars_to_loop[0]].time},
     49                 )
     50 

~/miniconda3/lib/python3.7/site-packages/xarray/core/dataarray.py in __init__(self, data, coords, dims, name, attrs, indexes, fastpath)
    342             data = _check_data_shape(data, coords, dims)
    343             data = as_compatible_data(data)
--> 344             coords, dims = _infer_coords_and_dims(data.shape, coords, dims)
    345             variable = Variable(dims, data, attrs, fastpath=True)
    346             indexes = dict(

~/miniconda3/lib/python3.7/site-packages/xarray/core/dataarray.py in _infer_coords_and_dims(shape, coords, dims)
    121         raise ValueError(
    122             "different number of dimensions on data "
--> 123             "and dims: %s vs %s" % (len(shape), len(dims))
    124         )
    125     else:

ValueError: different number of dimensions on data and dims: 2 vs 1
```

The problem is that the loop_dim is still in the dataset, but the code executes the `else` case, where only a time dim is assumed
```python
            if len(loop_dim_id_list) > 1:
...
            else:
                return xr.DataArray(
                    data=func(**kwargs),
                    dims=("time"),
                    coords={"time": kwargs[vars_to_loop[0]].time},
                )
```

Can we just add the loop dim to dims in the `else` case?

**Comment by cchwala** [comment]
Yes, the xarray wrapper is a bit limited to one specific type of xr.Dataset for storing CML data. This need improvement.

> Can we just add the loop dim to dims in the else case?

Quickly thinking through my convoluted code for the wrapper, I guess this would not work because the `else` should cover the case where there is no dimension other than `time`. If you add the loop dim to the `else` case you would get back a xr.Dataset with different dimension from what you have provided as input.

Maybe the whole approach with specifying `loop_dim` was not a good choice anyway, because we do use the same value for `loop_dim` everywhere we use the wrapper. But people might want to call there `channel_id` dimension differently, e.g. `sublink_id` or something else. Hence, it seems to me that a better solution would be to do more or less something like a "apply-along-time-dimension-logic", i.e. look for the time dimension and iterate over potential other dimension (maybe only allow one other dimension). That would avoid dealing with different names of the "channel" dimension, or with its absence.

I also always thought that there must be an easier way in xarray to do what the wrapper does right now, e.g. with using [`apply_ufunc`](http://xarray.pydata.org/en/stable/generated/xarray.apply_ufunc.html) or something else that applies a function along a certain dimension, but I have not found such a solution.

If you want to try out a new solutoin, feel free to provide a WIP PR, at best with a failing test for the problem you describe above.
